---
# 1. 速度指令 (ROS 控制器 -> Gazebo)
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# 2. 里程计 (Gazebo 底盘 -> ROS)
- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# 3. 激光雷达数据 (Gazebo 传感器 -> ROS)，原始数据发布到 /scan，过滤后为 /scan_filtered
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS #Gazebo 传感器 -> ROS

# 4. TF 坐标树 (Gazebo 物理引擎 -> ROS)
# 这一步极其关键，把 Gazebo 计算好的 odom -> base_link 传递给 ROS 系统
- ros_topic_name: "/tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# 5. 虚拟时间同步 (让 ROS 使用 Gazebo 里面的流逝时间)
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS