---
# 1. 速度指令 (ROS 控制器 -> Gazebo)
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# 2. 里程计 (Gazebo 底盘 -> ROS)
- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# 3. 激光雷达数据 (Gazebo 传感器 -> ROS)，原始数据发布到 /scan，过滤后为 /scan_filtered
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS #Gazebo 传感器 -> ROS

# 4. TF 坐标树 (Gazebo 物理引擎 -> ROS)
# 这一步极其关键，把 Gazebo 计算好的 odom -> base_link 传递给 ROS 系统
# 使用EKF生成 odom -> base_link
# - ros_topic_name: "/tf"
#   gz_topic_name: "/tf"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS

# 5. 虚拟时间同步 (让 ROS 使用 Gazebo 里面的流逝时间)
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# 6. IMU数据 (Gazebo 传感器 -> ROS)
- ros_topic_name: "/imu/data_raw"
  gz_topic_name: "/imu/data_raw"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS


# ====== RealSense D435 RGB 彩色图像 ======
- ros_topic_name: "/d435/color/image_raw"
  gz_topic_name: "/d435/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# ====== RealSense D435 深度图像 ======
- ros_topic_name: "/d435/depth/image_raw"
  gz_topic_name: "/d435/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# ====== RealSense D435 3D 点云 ======
- ros_topic_name: "/d435/depth/color/points"
  gz_topic_name: "/d435/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS


# ====== 关节状态 (Gazebo 物理引擎 -> ROS 2) ======
# 将底盘车轮和机械臂的关节角度同步给 robot_state_publisher，用于发布完整的 TF 树
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/testing_world/model/leo_sim/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
