ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    
    # Frames
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_footprint"
    world_frame: "odom"

    # Odom config
    odom0: "/odom"
    # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    odom0_config: [true, true, false, false, false, true, true, false, false, false, false, true, false, false, false]
    odom0_differential: false

    # IMU config
    imu0: "/imu/data_raw"
    # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    imu0_config: [false, false, false, false, false, true, false, false, false, false, false, true, true, true, false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true