ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    
    # Frames
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_footprint"
    world_frame: "odom"

    # Odom config
    odom0: "/odom"
    # 融合：X, Y, Yaw, vX
    # 关掉 vYaw，把角速度的融合工作交给更精准的 IMU
    # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    odom0_config: [true, true, false, false, false, true, true, false, false, false, false, false, false, false, false]
    odom0_differential: false

    # IMU config
    imu0: "/imu/data_raw"
    # 仅融合：vYaw (Z轴角速度)
    # 如果小车急加速容易打滑，可以开启 ax (X轴线加速度)，否则建议把 ax 和 ay 也设为 false，只用 IMU 的角速度。
    # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    imu0_config: [false, false, false, false, false, false, false, false, false, false, false, true, false, false, false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true